config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: :json} do
    resources :posts, only: [:index, :create, :show, :destroy, :edit, :update]
    resources :users, only: [:index, :show]
    resources :follows, only: [:index, :create, :destroy]
  end
  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new]

  root to: "static_pages#root"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :author_id, :post_id, presence: true

  belongs_to :post,
  primary_key: :id,
  foreign_key: :post_id,
  class_name: "Post"

  belongs_to :author,
  primary_key: :id,
  foreign_key: :author_id,
  class_name: "User"
  
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  validates :follower_id, :followed_id, presence: true

  belongs_to :follower,
  primary_key: :id,
  foreign_key: :follower_id,
  class_name: "User"

  belongs_to :followee,
  primary_key: :id,
  foreign_key: :followed_id,
  class_name: "User"
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :author_id, :picture_URL, presence: true

  has_many :comments,
  primary_key: :id,
  foreign_key: :post_id,
  class_name: "Comment"


  def self.own_posts(id)
    self.where("author_id = ?", id)
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true

  after_initialize :ensure_session_token

  has_many :follows,
  primary_key: :id,
  foreign_key: :follower_id,
  class_name: "Follow"

  has_many :followees,
  through: :follows,
  source: :followee

  has_many :followers,
  through: :follows,
  source: :follower

  has_many :posts,
  primary_key: :id,
  foreign_key: :author_id,
  class_name: "Post"

  has_many :comments,
  primary_key: :id,
  foreign_key: :author_id,
  class_name: "Comment"


  def find_latest
    self.posts.last
  end


  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/api/feeds_controller.rb
class Api::FeedsController < ApplicationController

  def show
    @post = User.find_latest(params[:id])
    if @post
      render :show
    else
      render "no posts".json
    end
  end
end

app/controllers/api/follows_controller.rb
class Api::FollowsController < ApplicationController
  def index
    @followed = current_user.followees.includes(:posts)
    render :index
  end

  def create
    @follow = Follow.new(follow_params)
    @follow.follower_id = current_user.id
    if @follow.save!
      @user = @follow.followee
      render :show
    end
  end

  def destroy
    @follow = Follow.find_by(followed_id: params[:id], follower_id: current_user.id)
    @user = @follow.followee
    @follow.destroy
    render :show
  end

  private

  def follow_params
    params.require(:follow).permit(:followed_id)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    @posts = Post.own_posts(params[:author_id])
    render :index
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save!
      render :show
    end
  end

  def edit
    @post = Post.find(params[:id])
    @comment = Comment.find(params[:comment][:id])
    @comment.destroy
    render :show
  end

  def update
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    if @comment.save!
      @post = @comment.post
      render :show
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    render :show
  end

  private

  def post_params
    params.require(:post).permit(:picture_URL, :public_id, :caption)
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?

  private

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_user!
    redirect_to new_user_url if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      flash.now[:errors] = ["Incorrect username and/or password"]
      render :new
    else
      login_user!(user)
      redirect_to root_url
    end
  end

  def destroy
    logout_user!
    render json: {}
  end

  def new
    render :new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_user!

  def root
    render :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def show
    @user = current_user
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end



end

app/helpers/api/feeds_helper.rb
module Api::FeedsHelper
end

app/helpers/api/follows_helper.rb
module Api::FollowsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DaguerreoTyp</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= csrf_meta_tags %>
  <script src="https://widget.cloudinary.com/global/all.js" type="text/javascript" charset="utf-8"></script>
  <link href='https://fonts.googleapis.com/css?family=Old+Standard+TT:400,400italic,700' rel='stylesheet' type='text/css'>
  <script type="text/javascript" charset="utf-8">
    window.current_username = '<%= current_user.username if current_user %>'
    window.current_userid = '<%= current_user.id if current_user %>'
    window.CLOUDINARY_OPTIONS = {
      cloud_name: "<%=ENV['CLOUD_NAME']%>",
      upload_preset: "<%= ENV['UPLOAD_PRESET'] %>"
    };
  </script>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

app/views/static_pages/root.html.erb
<div id="content">
</div>
<%= javascript_include_tag 'application' %>

app/views/users/new.html.erb
<div class="logins_container">
  <h1 class="logins_header">Welcome to DaguerreoTyp</h1>

  <div class="logins">
    <%= render "shared/errors" %>

    <form action="<%= users_url %>" method="post" class="logins">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

      <input type="text"
             placeholder=" username"
             name="user[username]"
             id="user_username"
             value="<%= @user.username %>">
      <br>

      <input type="password"
             placeholder=" password"
             name="user[password]"
             id="user_password"
             value="<%= @user.password %>">
      <br>
      <input class="login_submit_button" type="submit">

    </form>
    <form action="<%= session_url %>" method="post">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

      <input type="hidden" placeholder="username" name="user[username]" value="Juraj" id="user_username">
      <br>

      <input type="hidden" placeholder="password" name="user[password]" value="qwerty" id="user_password">
      <br>

      <button class="guest_button">Sign in as Guest</button>
    </form>
  </div>
  <div class="logins_switch">
    <%= link_to "Already a Daguerreotypist? Sign In!", new_session_url %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %>!</h1>